export const buildRestaurant = (overrides: Record<string, any> = {}) => ({
  id: 'restaurant-uuid',
  name: 'Tandoori Palace',
  slug: 'tandoori-palace',
  logoUrl: null,
  ownerName: 'Test Owner',
  ownerEmail: 'owner@test.com',
  phone: '+911234567890',
  address: 'Test Address',
  subscriptionStatus: 'active',
  isActive: true,
  maxTables: 10,
  createdAt: new Date(),
  updatedAt: new Date(),
  deletedAt: null,
  settings: {
    id: 'settings-uuid',
    restaurantId: 'restaurant-uuid',
    isVegOnly: false,
    allowUpiPayments: true,
    allowWaiterCall: true,
    cgstRate: 2.5,
    sgstRate: 2.5,
    serviceChargeRate: 5.0,
    allowedFoodTypes: ['VEG', 'NON_VEG', 'EGG', 'VEGAN', 'JAIN'],
  },
  ...overrides,
});

export const buildTable = (overrides: Record<string, any> = {}) => ({
  id: 'table-uuid',
  restaurantId: 'restaurant-uuid',
  name: 'T1',
  status: 'VACANT',
  activeSessionId: null,
  isActive: true,
  qrCodeUrl: null,
  createdAt: new Date(),
  updatedAt: new Date(),
  ...overrides,
});
